---
- name: 'Create {{container_name}} container'
  docker_container:
    name: '{{container_name}}'
    image: '{{beacon_node_cont_image}}'
    pull: true
    restart_policy: always
    state: 'started'
    recreate: false
    restart: false
    ports:
      - '127.0.0.1:{{public_tcp_port}}:{{beacon_node_listening_port}}'
      - '127.0.0.1:{{public_udp_port}}:{{beacon_node_disovery_port}}/udp'
      - '{{public_tcp_port}}:{{beacon_node_listening_port}}'
      - '{{public_udp_port}}:{{beacon_node_disovery_port}}/udp'
    command: |
      {% if beacon_node_verbose %}
      --logLevel=DEBUG
      {% endif %}
      --network={{beacon_node_network}}
      --tcpPort={{beacon_node_listening_port}}
      --udpPort={{beacon_node_disovery_port}}
    volumes:
      - '{{beacon_node_cont_vol}}/node-{{index}}:/root/.cache/nimbus'

- name: 'Enable TCP port for beacon node {{index}}'
  iptables:
    comment: 'TCP port for beacon node {{index}}'
    action: insert
    chain: DOCKER-USER
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: 'tcp'
    destination_port: '{{public_tcp_port}}'
  notify:
    - Save iptables rules

- name: 'Enable UDP port for beacon node {{index}}'
  iptables:
    comment: 'UDP port for beacon node {{index}}'
    action: insert
    chain: DOCKER-USER
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: 'udp'
    destination_port: '{{public_udp_port}}'
  notify:
    - Save iptables rules

