---
- name: 'Create {{ beacon_node_cont_name }} container'
  docker_container:
    name: '{{ beacon_node_cont_name }}'
    image: '{{ beacon_node_cont_image }}'
    pull: true
    restart_policy: always
    state: 'started'
    recreate: false
    restart: false
    ports:
      - '127.0.0.1:{{ beacon_node_cont_listening_port }}:{{ beacon_node_cont_listening_port }}'
      - '{{ beacon_node_cont_listening_port }}:{{ beacon_node_cont_listening_port }}'
      - '{{ beacon_node_cont_disovery_port }}:{{ beacon_node_cont_disovery_port }}/udp'
    command: |
      {% if nimbus_verbose %}
      --logLevel=DEBUG
      {% endif %}
      --tcpPort={{ beacon_node_cont_listening_port }}
      --udpPort={{ beacon_node_cont_disovery_port }}
    volumes:
      - '{{ beacon_node_cont_vol }}/data:/root/.lpData'
