---
- name: 'Create container dir: {{ beacon_node_cont_name }}'
  file:
    path: '{{ beacon_node_cont_vol }}/data'
    state: directory
    owner: dockremap
    group: docker

- name: 'Create container: {{ beacon_node_cont_name }}'
  docker_container:
    name: '{{ beacon_node_cont_name }}'
    image: '{{ beacon_node_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    # enable image updates via watchtower
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - '{{ beacon_node_metrics_port }}:{{ beacon_node_metrics_port }}/tcp'
      - '{{ beacon_node_public_tcp_port }}:{{ beacon_node_listening_port }}/tcp'
      - '{{ beacon_node_public_udp_port }}:{{ beacon_node_discovery_port }}/udp'
    command: |
      --eth1-network
      --log-level={{ beacon_node_log_level }}
      --tcp-port={{ beacon_node_listening_port }}
      --udp-port={{ beacon_node_discovery_port }}
      {% if beacon_node_metrics_enabled %}
      --metrics-server=on
      --metrics-server-address=0.0.0.0
      --metrics-server-port={{ beacon_node_metrics_port }}
      {% endif %}
    volumes:
      - '{{ beacon_node_cont_vol }}/data:/root/.cache/nimbus'
