---
- name: 'Create container dir: {{ beacon_node_cont_name }}'
  file:
    path: '{{ beacon_node_cont_vol }}/data'
    state: directory
    owner: dockremap
    group: docker

- name: 'Create container config: {{ beacon_node_cont_name }}'
  set_fact:
    beacon_node_compose:
      version: '3.7'
      services:
        beacon_node:
          container_name: '{{ beacon_node_cont_name }}'
          image: '{{ beacon_node_cont_image }}'
          restart: 'always'
          ports:
            - '{{ beacon_node_metrics_port }}:{{ beacon_node_metrics_port }}/tcp'
            - '{{ beacon_node_listening_port }}:{{ beacon_node_listening_port }}/tcp'
            - '{{ beacon_node_discovery_port }}:{{ beacon_node_discovery_port }}/udp'
          command:
            - '--nat=extip:{{ beacon_node_public_address }}'
            - '--log-level={{ beacon_node_log_level }}'
            - '--tcp-port={{ beacon_node_listening_port }}'
            - '--udp-port={{ beacon_node_discovery_port }}'
            - '--metrics-server=on'
            - '--metrics-server-address=0.0.0.0'
            - '--metrics-server-port={{ beacon_node_metrics_port }}'
          volumes:
            - '{{ beacon_node_cont_vol }}/data:/root/.cache/nimbus'

- name: 'Create compose file: {{ beacon_node_cont_name }}'
  copy:
    dest: '{{ beacon_node_cont_vol }}/docker-compose.yml'
    content: '{{ beacon_node_compose | to_nice_yaml }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create container: {{ beacon_node_cont_name }}'
  docker_compose:
    project_src: '{{ beacon_node_cont_vol }}'
    state: '{{ compose_state }}'
    recreate: '{{ compose_recreate }}'
    restarted: '{{ compose_restart }}'
    pull: true
    build: no
