---
- name: 'Create compose file: {{ beacon_node_cont_name }}'
  copy:
    dest: '{{ beacon_node_cont_vol }}/docker-compose.yml'
    content: '{{ beacon_node_compose | to_nice_yaml }}'
    owner: dockremap
    group: docker
    mode: 0644

# --compatibility flag required for mem/cpu limits
- name: 'Create container: {{ beacon_node_cont_name }}'
  command: >-
    docker-compose
      --compatibility
      up
      --quiet-pull
      --no-build
      {% if compose_recreate %}
      --force-recreate
      {% endif %}
      --no-color
      -d
  args:
    chdir: '{{ beacon_node_cont_vol }}'
  when: cont_restart

