---
- name: 'Create compose file: {{ beacon_node_cont_name }}'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ beacon_node_cont_vol }}/docker-compose.yml'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create container: {{ beacon_node_cont_name }}'
  docker_compose:
    project_src: '{{ beacon_node_cont_vol }}'
    recreate: '{{ compose_recreate | ternary("always", "smart") }}'
    pull: true
